### ISSUE TITLE
All games that have binaries marked for admin execution crash Playnite

### ISSUE THREAD

**Issue by instinctualjealousy** [hawkeye116477/playnite-gog-oss-plugin#24]
### Prerequisites

- [X] I've looked through [existing issues](https://github.com/hawkeye116477/playnite-gog-oss-plugin/issues) to make sure that this bug hasn't been reported before.
- [X] I've read the [GitHub Community Guidelines](https://docs.github.com/en/github/site-policy/github-community-guidelines) and know netiquette.

### Playnite version

10.34.0.23368

### Plugin version

1.1.2.35338

### Comet version

0.1.2

### Gogdl version

1.1.2

### Bug description

This affects many older games that have RUNASADMIN enabled in the registry for compatibility reasons (also XP compatibility has inherent admin privileges.)

This might affect your other plugins, but I wouldn't know as I've never run into it there.

### Relevant log
```
20-11 15:11:09.181|ERROR|PlayniteApplication:Unhandled exception occured.
System.ComponentModel.Win32Exception (0x80004005): Failed to start a process with file path 'D:\GOGLibrary\Jade Empire\JadeEmpire.exe'. Target file or working directory doesn't exist, or the provided credentials are invalid. ---> System.ComponentModel.Win32Exception (0x80004005): The requested operation requires elevation
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at CliWrap.Utils.ProcessEx.Start()
   at CliWrap.Utils.ProcessEx.Start()
   at CliWrap.Command.ExecuteAsync(CancellationToken forcefulCancellationToken, CancellationToken gracefulCancellationToken)
   at CliWrap.EventStream.EventStreamCommandExtensions.<ListenAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at CliWrap.EventStream.EventStreamCommandExtensions.<ListenAsync>d__0.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at GogOssLibraryNS.GogOssPlayController.<LaunchGame>d__14.MoveNext() in Dev:/playnite-gog-oss-plugin/src/GogOssGameController.cs:line 480
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at GogOssLibraryNS.GogOssPlayController.<LaunchGame>d__14.MoveNext() in Dev:/playnite-gog-oss-plugin/src/GogOssGameController.cs:line 480
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at GogOssLibraryNS.GogOssPlayController.<Play>d__10.MoveNext() in Dev:/playnite-gog-oss-plugin/src/GogOssGameController.cs:line 247
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Playnite.DesktopApp.ProgramEntry.Main(String[] args) in C:\projects\playnite\source\Playnite.DesktopApp\ProgramEntry.cs:line 71
```
### Screenshots

![image](https://github.com/user-attachments/assets/7c84fe7b-736a-40c1-9809-da5a3173107c)

**Comment by hawkeye116477** [comment]
I'll see later what can be done. However that looks like a big problem, cuz we're still on old .Net 4, so we can't have nice [ArgumentsList](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.argumentlist?view=net-9.0) and CliWrap isn't supporting admin things, so I'll either need modify Process or CliWrap.


> This might affect your other plugins, but I wouldn't know as I've never run into it there.

In case of other plugins, that's job of launcher binaries, so no fix is needed from plugin side.

**Comment by hawkeye116477** [comment]
Ok. I found a way. Check if it works (remove .zip from filename).
[GogOssLibrary_1_1_2_32150.pext.zip](https://github.com/user-attachments/files/17873591/GogOssLibrary_1_1_2_32150.pext.zip)

**Comment by instinctualjealousy** [comment]
That seems to fix it for me!
